apiVersion: 1

datasources:
  - name: Sudowork Log ClickHouse
    uid: sudo-log-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      server: ${CLICKHOUSE_HOST}
      port: ${CLICKHOUSE_PORT}
      protocol: http
      defaultDatabase: ${GRAFANA_CLICKHOUSE_DATABASE}
      username: ${GRAFANA_CLICKHOUSE_USER}
      tlsSkipVerify: false
    secureJsonData:
      password: ${GRAFANA_CLICKHOUSE_PASSWORD}
